apiVersion: v1
kind: Service
metadata:
  name: pv-avif-converter-service
  namespace: pv
  labels:
    app: pv-avif-converter
spec:
  selector:
    app: pv-avif-converter
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  type: LoadBalancer
