apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-slask-pv
  labels: {}
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: ""
  nfs:
    server: mjolnir
    path: /mnt/storage/slask/pv
    readOnly: false