apiVersion: v1
kind: Service
metadata:
  name: pv-api-service
  namespace: pv
  labels:
    app: pv-api
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.205
spec:
  selector:
    app: pv-api
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  type: LoadBalancer
